# -*- coding: utf-8 -*-
"""HW3-book-search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHL_ydY03bSUfHfpEiCR4cRsMvwV2laD
"""
# ==============================================================================

# Commented out IPython magic to ensure Python compatibility.
# %pip install numpy matplotlib imageio scikit-image>=0.25 scikit-learn ipywidgets ipykernel

# ==============================================================================

import skimage
import numpy as np
import imageio.v3 as iio
import cv2 as cv
import glob

from ipywidgets import interact, IntSlider
from matplotlib import pyplot as plt
from imageio.v3 import imread, imwrite
from skimage import transform, data
from skimage.color import rgb2gray
from skimage.feature import match_descriptors, plot_matched_features, SIFT

from tqdm import tqdm
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

# STEP 1 =======================================================================

# Load all images in the Children Books Director
paths = sorted(glob.glob('Childrens-Books/000039*.jpg'))
images = []
for p in tqdm(paths, desc='processing images'):
    images.append(skimage.color.rgb2gray(imread(p)))

# STEP 2 =======================================================================

SIFT_MODEL = SIFT()

def get_key_and_desc(img, sift=SIFT_MODEL):
  sift.detect_and_extract(img)
  keypoints = sift.keypoints
  descriptors = sift.descriptors

  return keypoints, descriptors

# Get all descriptors for all images
descriptors = []
for img in tqdm(images, desc='detecting keypoints'):
    descriptors.append(get_key_and_desc(img)[1])
all_descriptors = np.concatenate(descriptors)

# STEP 3 =======================================================================

# Cluster all descriptors into 1000 clusters
print('clustering descriptors with kmeans...')
kmeans = KMeans(n_clusters=1000, random_state=0, n_init="auto").fit(all_descriptors)
print('finished Clustering descriptors with kmeans!')

# STEP 4 =======================================================================

# Use the KMeans clustering to convert each list of SIFT descriptors into a 
# list of cluster labels (using .predict()).
cluster_labels = []
for desc in tqdm(descriptors, desc='converting to cluster labels'):
    cluster_labels.append(kmeans.predict(desc))

# STEP 5 =======================================================================

# Convert each list of cluster labels into a string (using str()). Now each 
# image has been converted into a "text document"
txt_documents = []
for label in tqdm(cluster_labels, desc='converting labels to strings'):
    txt_documents.append(str(label))


# STEP 6 =======================================================================

# Use sklearn.feature_extraction.text.TfidfVectorizer to convert each "document"
# to a tf-idf weighted histogram


print('converting documents to histograms...')
histograms = TfidfVectorizer().fit_transform(txt_documents)
print('finished converting documents to histograms!')

# STEP 7 =======================================================================

# Build a k nearest neighbors model on the histograms

knn_model = NearestNeighbors(metric='cosine')
knn_model.fit(histograms)

# STEP 8 =======================================================================
# STEP 9 =======================================================================
# STEP 10 ======================================================================

print(knn_model)
